Notes: Jenkins pipeline
project: crdc-dh
services:
  backend:
    version: 3.3.0.1100
    image: 3.3.0.1100
    buildNumber: '1100'
  frontend:
    version: 3.3.0.619
    image: 3.3.0.619
    buildNumber: '619'
    additionalProperties:
      uploadCliVersion: 4.0.0-alpha-7
  authn:
    version: 3.3.0.141
    image: 3.3.0.141
    buildNumber: '141'
  filevalidation:
    version: 3.3.0.342
    image: 3.3.0.342
    buildNumber: '342'
  essentialvalidation:
    version: 3.3.0.342
    image: 3.3.0.342
    buildNumber: '342'
  metadatavalidation:
    version: 3.3.0.344
    image: 3.3.0.344
    buildNumber: '344'
  exportvalidation:
    version: 3.3.0.342
    image: 3.3.0.342
    buildNumber: '342'
  pvpuller:
    version: 3.3.0.30
    image: 3.3.0.30
    buildNumber: '30'
    additionalProperties: null
