Notes: Jenkins pipeline
project: crdc-dh
services:
  backend:
    version: 3.1.0.662
    image: 3.1.0.662
    buildNumber: '662'
  frontend:
    version: 3.1.0.438
    image: 3.1.0.438
    buildNumber: '438'
    additionalProperties:
      uploadCliVersion: 1.2.0-alpha-4
  authn:
    version: 2.1.0.105
    image: 2.1.0.105
    buildNumber: '105'
  filevalidation:
    version: 3.1.0.226
    image: 3.1.0.226
    buildNumber: '226'
  essentialvalidation:
    version: 3.1.0.226
    image: 3.1.0.226
    buildNumber: '226'
  metadatavalidation:
    version: 3.1.0.226
    image: 3.1.0.226
    buildNumber: '226'
  exportvalidation:
    version: 3.1.0.226
    image: 3.1.0.226
    buildNumber: '226'
  pvpuller:
    version: 3.1.0.8
    image: 3.1.0.8
    buildNumber: '8'
    additionalProperties: null
