Notes: Jenkins pipeline
project: crdc-dh
services:
  backend:
    version: 3.2.0.764
    image: 3.2.0.764
    buildNumber: '764'
  frontend:
    version: 3.2.0.479
    image: 3.2.0.479
    buildNumber: '479'
    additionalProperties:
      uploadCliVersion: 3.2.0-alpha-2
  authn:
    version: 2.1.1.116
    image: 2.1.1.116
    buildNumber: '116'
  filevalidation:
    version: 3.2.0.262
    image: 3.2.0.262
    buildNumber: '262'
  essentialvalidation:
    version: 3.2.0.262
    image: 3.2.0.262
    buildNumber: '262'
  metadatavalidation:
    version: 3.2.0.262
    image: 3.2.0.262
    buildNumber: '262'
  exportvalidation:
    version: 3.2.0.262
    image: 3.2.0.262
    buildNumber: '262'
  pvpuller:
    version: 3.2.0.14
    image: 3.2.0.14
    buildNumber: '14'
    additionalProperties: null
