Notes: Jenkins pipeline
project: crdc-dh
services:
  backend:
    version: 3.0.0.424
    image: 3.0.0.424
    buildNumber: '424'
  frontend:
    version: 3.0.0.336
    image: 3.0.0.336
    buildNumber: '336'
    additionalProperties:
      uploadCliVersion: 1.1.0-alpha-7
  authn:
    version: 2.1.0.108
    image: 2.1.0.108
    buildNumber: '108'
  filevalidation:
    version: 2.0.0.121
    image: 2.0.0.121
    buildNumber: '121'
  essentialvalidation:
    version: 2.0.0.121
    image: 2.0.0.121
    buildNumber: '121'
  metadatavalidation:
    version: 2.0.0.127
    image: 2.0.0.127
    buildNumber: '127'
  exportvalidation:
    version: 2.0.0.121
    image: 2.0.0.121
    buildNumber: '121'
