Notes: Jenkins pipeline
project: crdc-dh
services:
  backend:
    version: 1.0.0.29
    image: 1.0.0.29
    buildNumber: '29'
  frontend:
    version: mvp-1.0.0.64
    image: mvp-1.0.0.64
    buildNumber: '64'
  authn:
    version: login.21
    image: login.21
    buildNumber: '21'
  authz:
    version: 1.0.0.8
    image: 1.0.0.8
    buildNumber: '8'
