Notes: Jenkins pipeline
project: crdc-dh
services:
  backend:
    version: 3.2.0.856
    image: 3.2.0.856
    buildNumber: '856'
  frontend:
    version: 3.2.0.518
    image: 3.2.0.518
    buildNumber: '518'
    additionalProperties:
      uploadCliVersion: 3.2.0-alpha-3
  authn:
    version: 2.1.1.116
    image: 2.1.1.116
    buildNumber: '116'
  filevalidation:
    version: 3.2.0.277
    image: 3.2.0.277
    buildNumber: '277'
  essentialvalidation:
    version: 3.2.0.277
    image: 3.2.0.277
    buildNumber: '277'
  metadatavalidation:
    version: 3.2.0.277
    image: 3.2.0.277
    buildNumber: '277'
  exportvalidation:
    version: 3.2.0.277
    image: 3.2.0.277
    buildNumber: '277'
  pvpuller:
    version: 3.2.0.17
    image: 3.2.0.17
    buildNumber: '17'
    additionalProperties: null
