Notes: Jenkins pipeline
project: crdc-dh
services:
  backend:
    version: 1.0.0.41
    image: 1.0.0.41
    buildNumber: '41'
  frontend:
    version: mvp-1.0.0.78
    image: mvp-1.0.0.78
    buildNumber: '78'
  authn:
    version: login.22
    image: login.22
    buildNumber: '22'
  authz:
    version: 1.0.0.9
    image: 1.0.0.9
    buildNumber: '9'
