Notes: Jenkins pipeline
project: crdc-dh
services:
  backend:
    version: 1.0.0.29
    image: 1.0.0.29
    buildNumber: '29'
  frontend:
    version: env.65
    image: env.65
    buildNumber: '65'
  authn:
    version: login.22
    image: login.22
    buildNumber: '22'
  authz:
    version: 1.0.0.8
    image: 1.0.0.8
    buildNumber: '8'
