Notes: Jenkins pipeline
project: crdc-dh
services:
  backend:
    version: 2.1.0.245
    image: 2.1.0.245
    buildNumber: '245'
  frontend:
    version: mvp-2.1.0.208
    image: mvp-2.1.0.208
    buildNumber: '208'
  authn:
    version: 1.0.0.90
    image: 1.0.0.90
    buildNumber: '90'
