Notes: Jenkins pipeline
project: crdc-dh
services:
  backend:
    version: 3.0.0.396
    image: 3.0.0.396
    buildNumber: '396'
  frontend:
    version: 3.0.0.316
    image: 3.0.0.316
    buildNumber: '316'
    additionalProperties:
      uploadCliVersion: 1.2.0-alpha-1
  authn:
    version: 2.1.0.108
    image: 2.1.0.108
    buildNumber: '108'
  filevalidation:
    version: 2.0.0.117
    image: 2.0.0.117
    buildNumber: '117'
  essentialvalidation:
    version: 2.0.0.117
    image: 2.0.0.117
    buildNumber: '117'
  metadatavalidation:
    version: 2.0.0.117
    image: 2.0.0.117
    buildNumber: '117'
  exportvalidation:
    version: 2.0.0.116
    image: 2.0.0.116
    buildNumber: '116'
