Notes: Jenkins pipeline
project: crdc-dh
services:
  backend:
    version: 1.0.0.68
    image: 1.0.0.68
    buildNumber: '68'
  frontend:
    version: mvp-1.0.0.98
    image: mvp-1.0.0.98
    buildNumber: '98'
  authn:
    version: 1.0.0.39
    image: 1.0.0.39
    buildNumber: '39'
  authz:
    version: 1.0.0.25
    image: 1.0.0.25
    buildNumber: '25'
