Notes: Jenkins pipeline
project: crdc-dh
services:
  backend:
    version: 1.0.0.66
    image: 1.0.0.66
    buildNumber: '66'
  frontend:
    version: mvp-1.0.0.97
    image: mvp-1.0.0.97
    buildNumber: '97'
  authn:
    version: 1.0.0.38
    image: 1.0.0.38
    buildNumber: '38'
  authz:
    version: 1.0.0.23
    image: 1.0.0.23
    buildNumber: '23'
