Notes: Jenkins pipeline
project: crdc-dh
services:
  backend:
    version: 3.1.0.697
    image: 3.1.0.697
    buildNumber: '697'
  frontend:
    version: 3.1.0.447
    image: 3.1.0.447
    buildNumber: '447'
    additionalProperties:
      uploadCliVersion: 1.2.0-alpha-4
  authn:
    version: 2.1.0.105
    image: 2.1.0.105
    buildNumber: '105'
  filevalidation:
    version: 3.1.0.239
    image: 3.1.0.239
    buildNumber: '239'
  essentialvalidation:
    version: 3.1.0.239
    image: 3.1.0.239
    buildNumber: '239'
  metadatavalidation:
    version: 3.1.0.242
    image: 3.1.0.242
    buildNumber: '242'
  exportvalidation:
    version: 3.1.0.240
    image: 3.1.0.240
    buildNumber: '240'
  pvpuller:
    version: 3.1.0.12
    image: 3.1.0.12
    buildNumber: '12'
    additionalProperties: null
