Notes: Jenkins pipeline
project: crdc-dh
services:
  backend:
    version: 3.1.0.682
    image: 3.1.0.682
    buildNumber: '682'
  frontend:
    version: 3.1.0.440
    image: 3.1.0.440
    buildNumber: '440'
    additionalProperties:
      uploadCliVersion: 1.2.0-alpha-4
  authn:
    version: 2.1.0.105
    image: 2.1.0.105
    buildNumber: '105'
  filevalidation:
    version: 3.1.0.230
    image: 3.1.0.230
    buildNumber: '230'
  essentialvalidation:
    version: 3.1.0.230
    image: 3.1.0.230
    buildNumber: '230'
  metadatavalidation:
    version: 3.1.0.230
    image: 3.1.0.230
    buildNumber: '230'
  exportvalidation:
    version: 3.1.0.228
    image: 3.1.0.228
    buildNumber: '228'
  pvpuller:
    version: 3.1.0.10
    image: 3.1.0.10
    buildNumber: '10'
    additionalProperties: null
