Notes: Jenkins pipeline
project: crdc-dh
services:
  backend:
    version: 2.1.0.405
    image: 2.1.0.405
    buildNumber: '405'
  frontend:
    version: mvp-2.1.0.333
    image: mvp-2.1.0.333
    buildNumber: '333'
    additionalProperties:
      uploadCliVersion: 1.1.0-alpha-7
  authn:
    version: 2.1.0.105
    image: 2.1.0.105
    buildNumber: '105'
  filevalidation:
    version: 1.0.0.129
    image: 1.0.0.129
    buildNumber: '129'
  essentialvalidation:
    version: 1.0.0.136
    image: 1.0.0.136
    buildNumber: '136'
  metadatavalidation:
    version: 1.0.0.135
    image: 1.0.0.135
    buildNumber: '135'
  exportvalidation:
    version: 1.0.0.129
    image: 1.0.0.129
    buildNumber: '129'
