Notes: Jenkins pipeline
project: crdc-dh
services:
  backend:
    version: 3.0.0.382
    image: 3.0.0.382
    buildNumber: '382'
  frontend:
    version: 3.0.0.310
    image: 3.0.0.310
    buildNumber: '310'
    additionalProperties:
      uploadCliVersion: 1.1.0-alpha-4
  authn:
    version: 2.1.0.108
    image: 2.1.0.108
    buildNumber: '108'
  filevalidation:
    version: 2.0.0.116
    image: 2.0.0.116
    buildNumber: '116'
  essentialvalidation:
    version: 2.0.0.116
    image: 2.0.0.116
    buildNumber: '116'
  metadatavalidation:
    version: 2.0.0.116
    image: 2.0.0.116
    buildNumber: '116'
  exportvalidation:
    version: 2.0.0.115
    image: 2.0.0.115
    buildNumber: '115'
