Notes: Jenkins pipeline
project: crdc-dh
services:
  backend:
    version: 3.0.0.520
    image: 3.0.0.520
    buildNumber: '520'
  frontend:
    version: 3.0.0.377
    image: 3.0.0.377
    buildNumber: '377'
    additionalProperties:
      uploadCliVersion: 1.2.0-alpha-3
  authn:
    version: 2.1.1.116
    image: 2.1.1.116
    buildNumber: '116'
  filevalidation:
    version: 2.0.0.180
    image: 2.0.0.180
    buildNumber: '180'
  essentialvalidation:
    version: 2.0.0.180
    image: 2.0.0.180
    buildNumber: '180'
  metadatavalidation:
    version: 2.0.0.177
    image: 2.0.0.177
    buildNumber: '177'
  exportvalidation:
    version: 2.0.0.177
    image: 2.0.0.177
    buildNumber: '177'
