Notes: Jenkins pipeline
project: crdc-dh
services:
  backend:
    version: 3.4.0.59
    image: 3.4.0.59
    buildNumber: '59'
  frontend:
    version: 3.4.0.26
    image: 3.4.0.26
    buildNumber: '26'
    additionalProperties:
      uploadCliVersion: 4.1.0-alpha-2
  authn:
    version: 3.3.0.141
    image: 3.3.0.141
    buildNumber: '141'
  filevalidation:
    version: 3.4.0.5
    image: 3.4.0.5
    buildNumber: '5'
  essentialvalidation:
    version: 3.4.0.5
    image: 3.4.0.5
    buildNumber: '5'
  metadatavalidation:
    version: 3.4.0.5
    image: 3.4.0.5
    buildNumber: '5'
  exportvalidation:
    version: 3.4.0.5
    image: 3.4.0.5
    buildNumber: '5'
  pvpuller:
    version: 3.3.0.30
    image: 3.3.0.30
    buildNumber: '30'
    additionalProperties: null
