Notes: Jenkins pipeline
project: crdc-dh
services:
  backend:
    version: 3.0.0.479
    image: 3.0.0.479
    buildNumber: '479'
  frontend:
    version: 3.0.0.369
    image: 3.0.0.369
    buildNumber: '369'
    additionalProperties:
      uploadCliVersion: 1.2.0-alpha-2
  authn:
    version: 2.1.1.116
    image: 2.1.1.116
    buildNumber: '116'
  filevalidation:
    version: 2.0.0.167
    image: 2.0.0.167
    buildNumber: '167'
  essentialvalidation:
    version: 2.0.0.167
    image: 2.0.0.167
    buildNumber: '167'
  metadatavalidation:
    version: 2.0.0.167
    image: 2.0.0.167
    buildNumber: '167'
  exportvalidation:
    version: 2.0.0.167
    image: 2.0.0.167
    buildNumber: '167'
