Notes: Jenkins pipeline
project: crdc-dh
services:
  backend:
    version: 2.0.0.133
    image: 2.0.0.133
    buildNumber: '133'
  frontend:
    version: mvp-1.0.0.130
    image: mvp-1.0.0.130
    buildNumber: '130'
  authn:
    version: 1.0.0.61
    image: 1.0.0.61
    buildNumber: '61'
  authz:
    version: 2.0.0.48
    image: 2.0.0.48
    buildNumber: '48'
