Notes: Jenkins pipeline
project: crdc-dh
services:
  backend:
    version: 3.3.0.1050
    image: 3.3.0.1050
    buildNumber: '1050'
  frontend:
    version: 3.3.0.592
    image: 3.3.0.592
    buildNumber: '592'
    additionalProperties:
      uploadCliVersion: 4.0.0-alpha-4
  authn:
    version: 2.1.3.137
    image: 2.1.3.137
    buildNumber: '137'
  filevalidation:
    version: 3.3.0.317
    image: 3.3.0.317
    buildNumber: '317'
  essentialvalidation:
    version: 3.3.0.317
    image: 3.3.0.317
    buildNumber: '317'
  metadatavalidation:
    version: 3.3.0.317
    image: 3.3.0.317
    buildNumber: '317'
  exportvalidation:
    version: 3.3.0.317
    image: 3.3.0.317
    buildNumber: '317'
  pvpuller:
    version: 3.2.0.24
    image: 3.2.0.24
    buildNumber: '24'
    additionalProperties: null
