Notes: Jenkins pipeline
project: crdc-dh
services:
  backend:
    version: 3.1.0.697
    image: 3.1.0.697
    buildNumber: '697'
  frontend:
    version: 3.1.0.449
    image: 3.1.0.449
    buildNumber: '449'
    additionalProperties:
      uploadCliVersion: 1.2.0-alpha-4
  authn:
    version: 2.1.0.105
    image: 2.1.0.105
    buildNumber: '105'
  filevalidation:
    version: 3.1.0.246
    image: 3.1.0.246
    buildNumber: '246'
  essentialvalidation:
    version: 3.1.0.246
    image: 3.1.0.246
    buildNumber: '246'
  metadatavalidation:
    version: 3.1.0.246
    image: 3.1.0.246
    buildNumber: '246'
  exportvalidation:
    version: 3.1.0.246
    image: 3.1.0.246
    buildNumber: '246'
  pvpuller:
    version: 3.1.0.12
    image: 3.1.0.12
    buildNumber: '12'
    additionalProperties: null
