Notes: Jenkins pipeline
project: crdc-dh
services:
  backend:
    version: 3.1.0.676
    image: 3.1.0.676
    buildNumber: '676'
  frontend:
    version: 3.1.0.439
    image: 3.1.0.439
    buildNumber: '439'
    additionalProperties:
      uploadCliVersion: 1.2.0-alpha-4
  authn:
    version: 2.1.0.105
    image: 2.1.0.105
    buildNumber: '105'
  filevalidation:
    version: 3.1.0.228
    image: 3.1.0.228
    buildNumber: '228'
  essentialvalidation:
    version: 3.1.0.228
    image: 3.1.0.228
    buildNumber: '228'
  metadatavalidation:
    version: 3.1.0.228
    image: 3.1.0.228
    buildNumber: '228'
  exportvalidation:
    version: 3.1.0.227
    image: 3.1.0.227
    buildNumber: '227'
  pvpuller:
    version: 3.1.0.9
    image: 3.1.0.9
    buildNumber: '9'
    additionalProperties: null
