Notes: Jenkins pipeline
project: crdc-dh
services:
  backend:
    version: 1.0.0.102
    image: 1.0.0.102
    buildNumber: '102'
  frontend:
    version: mvp-1.0.0.126
    image: mvp-1.0.0.126
    buildNumber: '126'
  authn:
    version: 1.0.0.57
    image: 1.0.0.57
    buildNumber: '57'
  authz:
    version: 1.0.0.37
    image: 1.0.0.37
    buildNumber: '37'
